spring.application.name=BootSecurityProj03-InMemoryDB-3.x-4.x


#View Resolver inputs
#spring.mvc.view.prefix=/WEB-INF/pages/
#spring.mvc.view.suffix=.jsp

#Embedded server port number
server.port=4041

# specify the context path of the application
server.servlet.context-path=/SecurityProj03