spring.application.name=BootSecurityProj04-ExternalDB-3.x-4.x


#View Resolver inputs
#spring.mvc.view.prefix=/WEB-INF/pages/
#spring.mvc.view.suffix=.jsp

#Embedded server port number
server.port=4041


# JDBC properties
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql:///spbms619db
spring.datasource.username=root
spring.datasource.password=Rajesh@8920


# specify the context path of the application
server.servlet.context-path=/SecurityProj04